-- =============================================================================
-- FIX: Return evidence images (uploaded by customers from the website) show a
--      broken icon everywhere.
-- Cause: they are stored in the 'images' bucket, whose `public` flag was only
--        set with ON CONFLICT DO NOTHING — if the bucket pre-existed (created
--        via dashboard), it stayed NON-public, so the /object/public/... URLs
--        generated by getPublicUrl() return 404.
-- Fix: force the bucket public.
-- =============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Verify: should return 1 row with public = true
-- SELECT id, name, public FROM storage.buckets WHERE id = 'images';